import gspread
import pandas as pd
from utils import gl_parser
from datetime import datetime

# Placeholder for config. This will eventually come from config_template.py
# For now, hardcode necessary tab names for development
class Config:
    TAB_REALIZED_GL = "Realized_GL"

# --- Google Sheets Interaction (Placeholder) ---
def get_worksheet(sheet_client, sheet_id, tab_name):
    """Retrieves a specific worksheet by sheet ID and tab name."""
    spreadsheet = sheet_client.open_by_id(sheet_id)
    return spreadsheet.worksheet(tab_name)

def append_rows_to_sheet(worksheet, data, header):
    """Appends rows to a Google Sheet, ensuring header is present."""
    # This is a simplified placeholder. Real implementation would handle:
    # 1. Reading existing data to dedup
    # 2. Batch updating
    # 3. Error handling
    print(f"Appending {len(data)} rows to {worksheet.title}")
    # Simulate writing header if sheet is empty (not fully robust)
    if worksheet.row_count < 1 or worksheet.cell(1,1).value == '':
         worksheet.append_row(header, value_input_option='USER_ENTERED')
    
    if data:
        worksheet.append_rows(data, value_input_option='USER_ENTERED')


def ingest_realized_gl(uploaded_file, sheet_client, sheet_id, dry_run=True):
    """
    Parse Schwab G/L CSV, dedup against Realized_GL tab, append new rows.
    Returns: {"parsed": int, "new": int, "skipped": int, "errors": list}
    """
    results = {"parsed": 0, "new": 0, "skipped": 0, "errors": []}

    try:
        # 1. Parse the uploaded CSV
        df_new_gl = gl_parser.parse_realized_gl(uploaded_file)
        results["parsed"] = len(df_new_gl)

        if df_new_gl.empty:
            results["errors"].append("No valid realized G/L data found in the uploaded file.")
            return results

        # Add import_date and sort
        df_new_gl['import_date'] = datetime.now().strftime("%Y-%m-%d")
        df_new_gl.sort_values(by="closed_date", ascending=True, inplace=True)

        if dry_run:
            print("DRY RUN: Realized G/L ingestion complete. No data written to Google Sheet.")
            print(f"Parsed {len(df_new_gl)} new realized G/L lots.")
            results["new"] = len(df_new_gl) # In dry run, all parsed are "new"
            return results

        # 2. Get existing data from Realized_GL tab
        # This part requires proper Google Sheets authentication and interaction
        gl_worksheet = get_worksheet(sheet_client, sheet_id, Config.TAB_REALIZED_GL)
        existing_data = gl_worksheet.get_all_records() # Assumes first row is header
        df_existing_gl = pd.DataFrame(existing_data)
        
        # Define the header based on the schema in REALIZED_GL_PARSER_SPEC.md
        # This should match the order of columns in the DataFrame generated by gl_parser
        # ['Ticker', 'Description', 'Closed Date', 'Opened Date', 'Holding Days', 'Quantity', 
        #  'Proceeds Per Share', 'Cost Per Share', 'Proceeds', 'Cost Basis', 'Unadjusted Cost', 
        #  'Gain Loss $', 'Gain Loss %', 'LT Gain Loss', 'ST Gain Loss', 'Term', 'Wash Sale', 
        #  'Disallowed Loss', 'Account', 'Is Primary Acct', 'Import Date', 'Fingerprint']
        
        # Ensure column order matches the schema for writing
        expected_cols = [
            'ticker', 'description', 'closed_date', 'opened_date', 'holding_days',
            'quantity', 'proceeds_per_share', 'cost_per_share', 'proceeds', 'cost_basis',
            'unadjusted_cost', 'gain_loss_dollars', 'gain_loss_pct', 'lt_gain_loss',
            'st_gain_loss', 'term', 'wash_sale', 'disallowed_loss', 'account',
            'is_primary_acct', 'import_date', 'fingerprint'
        ]
        
        # Ensure all expected columns are present in df_new_gl
        for col in expected_cols:
            if col not in df_new_gl.columns:
                df_new_gl[col] = None # Add missing columns, though gl_parser should provide them

        df_new_gl = df_new_gl[expected_cols]

        # 3. Deduplicate
        new_fingerprints = set(df_new_gl['fingerprint'])
        existing_fingerprints = set(df_existing_gl['fingerprint']) if not df_existing_gl.empty else set()

        to_append_df = df_new_gl[~df_new_gl['fingerprint'].isin(existing_fingerprints)]
        results["skipped"] = len(df_new_gl) - len(to_append_df)

        if not to_append_df.empty:
            # Convert DataFrame to list of lists for Gspread, exclude header
            rows_to_append = to_append_df.values.tolist()
            # The header is from the spec, needs to be manually defined here
            header = [
                'Ticker', 'Description', 'Closed Date', 'Opened Date', 'Holding Days',
                'Quantity', 'Proceeds Per Share', 'Cost Per Share', 'Proceeds', 'Cost Basis',
                'Unadjusted Cost', 'Gain Loss $', 'Gain Loss %', 'LT Gain Loss',
                'ST Gain Loss', 'Term', 'Wash Sale', 'Disallowed Loss', 'Account',
                'Is Primary Acct', 'Import Date', 'Fingerprint'
            ]
            append_rows_to_sheet(gl_worksheet, rows_to_append, header)
            results["new"] = len(rows_to_append)
            print(f"Successfully appended {len(rows_to_append)} new realized G/L lots.")
        else:
            print("No new realized G/L lots to append.")

    except Exception as e:
        results["errors"].append(f"An error occurred during G/L ingestion: {e}")
        import traceback
        print(traceback.format_exc())

    return results

