import pandas as pd
import logging
import streamlit as st
import config
from pydantic import BaseModel
from typing import List
from utils.gemini_client import ask_gemini, SAFETY_PREAMBLE
from utils.fmp_client import get_historical_pe, get_key_metrics, get_company_profile, get_financial_statements
from utils.finnhub_client import get_basic_financials
import yfinance as yf

VALUATION_SYSTEM_PROMPT = """
**SYSTEM PROMPT: MACRO-CYCLE FINANCIAL ANALYST AGENT**

**ROLE DEFINITION**
You are an AI financial analyst agent evaluating corporate financial statements (CapEx, R&D, and ROIC) through the lens of Carlota Perez’s Techno-Economic Super Cycle framework. Your objective is to identify whether a company is a foundational "infrastructure builder" of a new technological paradigm or a "speculative hype stock" generated by the financial casino economy.

---

### PART 1: TARGET BEHAVIORS OF WINNING COMPANIES (SYNERGY & DEPLOYMENT PHASES)
During the 'Synergy' and 'Deployment' phases, the chaotic installation of the new technology transitions into a period of harmonious, widespread economic expansion. You must evaluate companies against the following fundamental behaviors that characterize winners in this "golden age":

*   **Shift to Real Wealth Creation:** Winning companies abandon the pursuit of short-term capital gains in favor of steady, real growth in production and the generation of actual dividends. 
*   **Focus on Economies of Scale and Market Expansion:** Operations transition from fierce, destructive price competition to the formation of oligopolies that prioritize the steady expansion of mass consumer markets. 
*   **Process and Cost-Reduction Innovation:** Instead of seeking radical new product breakthroughs, successful firms concentrate on process improvements, reliability, and cost reductions to expand their market volume and achieve economies of scale. 
*   **Self-Sufficient Financing:** Companies increasingly rely on internally generated funds (retained earnings) and long-term borrowing to finance their capital requirements, resulting in a sharp reduction in new stock flotations.
*   **Exploitation of Installed Externalities:** Winners leverage the vast physical and technological infrastructure built during the preceding 'Frenzy' phase to deeply embed the new paradigm across all economic sectors.

---

### PART 2: AGENT EVALUATION RULES (METRIC ANALYSIS)
To distinguish a foundational "infrastructure builder" (driven by Production Capital) from a "speculative hype stock" (driven by Financial Capital), apply the following strict evaluation rules to the financial data.

#### 1. Capital Expenditures (CapEx) Evaluation
*   **The Infrastructure Builder Signal:** Look for **consistently high and growing CapEx** that signifies the intense, long-term physical or network build-out of the new technological paradigm. These companies are laying the "basic externalities" and capacity required for the dynamic expansion of the real economy. 
*   **The Speculative Hype Signal:** Flag companies with **low real CapEx relative to their massive market capitalization**. Speculative hype stocks often operate as "virtual" entities with hardly any physical assets, yet possess market valuations that dwarf established, asset-heavy corporations. Their capital is frequently diverted into acquisitions, stock buybacks, or paper assets rather than productive capacity.

#### 2. Research & Development (R&D) Spending Evaluation
*   **The Infrastructure Builder Signal:** R&D spending should reflect a clear transition from exploratory trial-and-error to **consolidation and "arrangements-for-use"**. Evaluate the R&D narrative: it must focus on **process innovations, quality improvement, and extreme cost reductions** in core inputs and infrastructure to expand the consumer base. 
*   **The Speculative Hype Signal:** Flag R&D that is either non-existent (financial manipulation vehicles) or entirely focused on continuous, radical, but unproven technological disruptions designed strictly to attract venture capital and inflate stock prices. Hype R&D bends its decisions to provide the "high short-term gains required by the stock market" rather than achieving operational scale.

#### 3. Return on Invested Capital (ROIC) Evaluation
*   **The Infrastructure Builder Signal:** ROIC must demonstrate a **recoupling of financial metrics with actual production**. Look for companies where ROIC is driven by operational efficiency, steady market penetration, and the ability to pay **real dividends** out of generated profits. Their returns are realistic and based on the long-term criteria of production capital.
*   **The Speculative Hype Signal:** Flag companies where purported "returns" are highly dependent on **asset inflation, exorbitant price/earnings ratios, and capital gains** completely divorced from the actual profits of the real economy. If the ROIC is artificially propped up by financial engineering, leveraged buy-outs, or questionable accounting practices designed to mask a lack of fundamental earnings, classify it as a speculative hype stock.
"""

class ValuationReport(BaseModel):
    narrative: str
    verdict: str
    signals: str
    metrics_summary: str

class AccumulationPlan(BaseModel):
    analysis: str
    shares_to_buy: str
    new_weight_pct: float
    entry_rationale: str
    risk_factors: List[str]
    trigger_condition: str

def get_valuation_snapshot(ticker: str) -> dict:
    """
    Returns current_pe, avg_5yr_pe, pe_discount_pct, is_below_average,
    plus rich metadata for narrative generation.
    """
    try:
        metrics = get_key_metrics(ticker)
        hist_pe = get_historical_pe(ticker, years=5)
        profile = get_company_profile(ticker)
        basic = get_basic_financials(ticker) 
        statements = get_financial_statements(ticker)
        
        # Detect FMP availability: both metrics and hist_pe must return real data
        fmp_available = bool(metrics) and not hist_pe.empty

        current_pe = metrics.get('pe_ratio')

        # Always attempt yfinance fallback for profile enrichment
        y_info = {}
        try:
            y_ticker = yf.Ticker(ticker)
            y_info = y_ticker.info
        except Exception as ye:
            logging.warning(f"yfinance fallback failed for {ticker}: {ye}")

        if current_pe is None or current_pe == 0:
            current_pe = y_info.get('trailingPE') or y_info.get('forwardPE')

        if not profile.get('market_cap'):
            profile['market_cap'] = y_info.get('marketCap', 0)
        if not profile.get('sector'):
            profile['sector'] = y_info.get('sector', 'Unknown')

        if current_pe is None:
            return {"error": f"No valuation data available for {ticker}"}

        # Historical P/E comparison — only valid when FMP provides multiple years of data
        if not hist_pe.empty:
            avg_pe = hist_pe['pe_ratio'].mean()
            pe_discount = ((avg_pe - current_pe) / avg_pe) * 100 if avg_pe else 0
            is_below_avg = current_pe < avg_pe
        else:
            # FMP historical unavailable — cannot make a valid historical comparison
            avg_pe = None
            pe_discount = None
            is_below_avg = None
        
        def _to_float(v, default=0.0):
            try:
                return float(v) if v is not None else default
            except:
                return default

        rev_per_share = _to_float(metrics.get('revenue_per_share'))
        roe = _to_float(metrics.get('roe'))
        eps_calc = rev_per_share * (roe / 100) if roe else 0.0

        return {
            "ticker": ticker,
            "current_pe": float(current_pe),
            "avg_5yr_pe": float(avg_pe) if avg_pe is not None else None,
            "pe_discount_pct": float(pe_discount) if pe_discount is not None else None,
            "is_below_average": is_below_avg,
            "fmp_unavailable": not fmp_available,
            "market_cap": _to_float(profile.get('market_cap')),
            "dividend_yield": _to_float(metrics.get('dividend_yield')),
            "eps": eps_calc,
            "sector": profile.get('sector', "Unknown"),
            "high_52w": _to_float(basic.get('52WeekHigh')),
            "low_52w": _to_float(basic.get('52WeekLow')),
            "forward_pe": _to_float(basic.get('forwardPE')),
            "capex": _to_float(statements.get('capital_expenditure')),
            "rd": _to_float(statements.get('research_and_development_expenses')),
            "roic": _to_float(statements.get('roic')),
            "net_income": _to_float(statements.get('net_income')),
            "op_income": _to_float(statements.get('operating_income'))
        }
    except Exception as e:
        logging.error(f"Valuation snapshot error for {ticker}: {e}")
        return {"error": str(e)}

def generate_rich_valuation_report(ticker: str, val_snap: dict) -> dict:
    """
    Uses Gemini to generate the Perplexity-style rich narrative.
    """
    hist_pe_line = (
        f"- 5-Year Avg P/E: {val_snap['avg_5yr_pe']:.2f} (Discount vs avg: {val_snap['pe_discount_pct']:.1f}%)"
        if val_snap.get('avg_5yr_pe') is not None
        else "- Historical P/E: Unavailable (FMP subscription required). Evaluate on absolute basis vs sector norms."
    )

    prompt = f"""
    Analyze the valuation of {ticker} ({val_snap['sector']}) through the lens of the Carlota Perez framework.

    Current Financial Metrics:
    - Market Cap: ${val_snap['market_cap']/1e9:.2f}B
    - Current P/E: {val_snap['current_pe']:.2f}
    - Forward P/E: {val_snap.get('forward_pe', 0):.2f}
    {hist_pe_line}
    - Dividend Yield: {val_snap['dividend_yield']:.2f}%
    - ROIC: {val_snap['roic']:.2f}%
    - CapEx (Recent Annual): ${val_snap['capex']/1e6:.2f}M
    - R&D (Recent Annual): ${val_snap['rd']/1e6:.2f}M
    - Operating Income: ${val_snap['op_income']/1e6:.2f}M
    - Net Income: ${val_snap['net_income']/1e6:.2f}M
    - 52W Range: {val_snap.get('low_52w', 0):.2f} — {val_snap.get('high_52w', 0):.2f}

    {"NOTE: Historical P/E data is unavailable." if val_snap.get('fmp_unavailable') else ""}

    Evaluate if this company is an "Infrastructure Builder" or a "Speculative Hype Stock".
    
    Provide a report with these exact sections (formatted in Markdown):

    ### {ticker} Valuation Verdict
    [A lead paragraph summarizing the verdict. Base it on current metrics and the Macro-Cycle framework.]

    #### Macro-Cycle Analysis
    [Evaluate the company's behavior regarding CapEx, R&D, and ROIC relative to the Perez framework.]

    #### Market Pricing & Signals
    [Discuss the current multiple vs growth expectations and sector peers.]

    #### Key Metrics Summary
    - Trailing P/E: {val_snap['current_pe']:.2f}
    - ROIC: {val_snap['roic']:.2f}%
    - Market Cap: ${val_snap['market_cap']/1e9:.2f}B
    """
    
    system_instruction = f"{SAFETY_PREAMBLE}\n\n{VALUATION_SYSTEM_PROMPT}\n\nYou are a senior equity valuation analyst. Provide a professional, high-signal valuation report mirroring the style of Perplexity Finance."
    
    try:
        res = ask_gemini(prompt, system_instruction=system_instruction, response_schema=ValuationReport)
        if res:
            return res.model_dump()
        return {"error": "AI failed to generate valuation report"}
    except Exception as e:
        return {"error": str(e)}

def scan_valuation_opportunities(holdings_df: pd.DataFrame, watchlist: list = None) -> list[dict]:
    """
    Scan top holdings or watchlist for PE discounts.
    """
    results = []
    tickers = holdings_df.nlargest(10, 'Weight')['Ticker'].tolist()
    if watchlist:
        tickers.extend([t for t in watchlist if t not in tickers])
        
    for t in tickers:
        if t in ['CASH_MANUAL', 'QACDS', 'Cash & Cash Investments']: continue
        snap = get_valuation_snapshot(t)
        if "error" not in snap and snap.get('is_below_average'):
            results.append(snap)
            
    return sorted(results, key=lambda x: x['pe_discount_pct'], reverse=True)

def generate_accumulation_plan(ticker: str, deploy_amount: float, valuation_data: dict, holdings_df: pd.DataFrame) -> dict:
    """
    Gemini JSON: analysis, shares_to_buy, new_weight_pct, entry_rationale.
    """
    avg_pe_text = (
        f"5yr Avg: {valuation_data['avg_5yr_pe']:.2f}, Discount: {valuation_data['pe_discount_pct']:.1f}% below average"
        if valuation_data.get('avg_5yr_pe') is not None
        else "historical avg P/E unavailable"
    )

    prompt = f"""
    Ticker: {ticker}
    Current P/E: {valuation_data['current_pe']:.2f} ({avg_pe_text}).
    ROIC: {valuation_data['roic']:.2f}%
    
    Investor wants to deploy ${deploy_amount:,.2f} into this position.
    
    Current Weight: {holdings_df[holdings_df['Ticker'] == ticker]['Weight'].iloc[0] if ticker in holdings_df['Ticker'].values else 0.0:.2f}%
    
    Suggest an accumulation plan through the lens of the Perez framework. Is this an entry into an infrastructure winner?
    Consider risk factors and provide a trigger condition.
    """
    
    system_instruction = f"{SAFETY_PREAMBLE}\n\n{VALUATION_SYSTEM_PROMPT}\n\nYou are a valuation and accumulation strategist. Help the investor build positions at attractive prices."
    
    try:
        res = ask_gemini(prompt, system_instruction=system_instruction, response_schema=AccumulationPlan)
        if res:
            return res.model_dump()
        return {"error": "AI failed to generate accumulation plan"}
    except Exception as e:
        logging.error(f"Accumulation plan error for {ticker}: {e}")
        return {"error": str(e)}
